server:
  port: 8090

dubbo:
  registry:
    address: zookeeper://10.176.164.90:2181
    #zookeeper://10.176.164.207:2181
    #zookeeper://127.0.0.1:2181
    #registry: zookeeper://10.176.164.76:2181
    check: true
  application:
    name: user-consumer
  protocol:
    port: 20880
    name: dubbo