server:
  port: 8090

dubbo:
  registry:
    protocol: zookeeper
    address: 10.176.164.116:2181
    #zookeeper://10.176.164.207:2181
    #zookeeper://127.0.0.1:2181
    #registry: zookeeper://10.176.164.76:2181
    check: false
  application:
    name: user-consumer
  protocol:
    port: 20880
    name: dubbo
  scan:
    base-packages: com.gtja.user.controller

rocketmq:
  producer:
    isOnOff: on
    groupName: vehicleProducerGroup1
    namesrvAddr: 127.0.0.1:9876
    #127.0.0.1:9876
    #10.176.164.86:9876
    #//根据自己的地址修改
    instanceName: vehicleProducer
    topic: topic2018
    tag: test
    maxMessageSize: 131072
    sendMsgTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2

  consumer:
    isOnOff: on
    namesrvAddr: 127.0.0.1:9876
    #127.0.0.1:9876
    #10.176.164.86:9876
    groupName: vehicleProducerGroup1
    topic: topic2018
    tag: test
    consumeThreadMin: 20
    consumeThreadMax: 64
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1